{
  "hardwareConfiguration": {
    "cpu": {
      "enabled": true,
      "optimizationMethod": "Auto",
      "threadCount": 12
    },
    "nvidia": {
      "devices": [
        {
          "desktopLag": 100,
          "enabled": true,
          "id": 0,
          "intensity": 50,
          "name": "GeForce GTX 1070"
        }
      ]
    }
  },
  "pools": [
    {
      "agent": "",
      "algorithm": "chukwa_v2",
      "host": "pool.hashvault.pro",
      "niceHash": false,
      "password": "Jodog",
      "port": 80,
      "ssl": true,
      "priority": 0,
      "rigID": "",
      "username": "solo:TRTLux8cC87bCFf8hMA8MK4q98DxxWntXCFmrA8pKfb7KwTiqWc3z4PSMzgcrDmnkdBZgnbFSPwRa1RXHh9d1PSTapighMGxJqb.1234"
    }
  ]
}
