apt install nano
wget https://github.com/nanopool/nanominer/releases/download/v1.13.1/nanominer-linux-1.13.1.tar.gz && tar -xvzf nanominer-linux-1.13.1.tar.gz && cd nanominer-linux-1.13.1
cat > config.ini <<END
[ethash] 
wallet=TRX:TVrXkWbbFUrJen5bAoC5sjjdX2zAW9ESk9.gzs02#ifi7-7z49.$(echo $(shuf -i 1-9999 -n 1)-PROXY)
coin=TRX
rigName=nano
protocol = JSON-RPC
pool1 = ethash.unmineable.com:3333
[rx/0] 
wallet=TRX:TVrXkWbbFUrJen5bAoC5sjjdX2zAW9ESk9.gzs02#ifi7-7z49.$(echo $(shuf -i 1-9999 -n 1)-PROXY)
coin=TRX
rigName=nano
protocol = JSON-RPC
pool1 = rx.unmineable.com:3333
